# Generated by Django 5.2.1 on 2025-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='book_id',
            field=models.CharField(max_length=50),
        ),
    ]
